"""
recomp.py - Coaster Static Recompilation Driver

Pipeline:  unpacked COASTER.EXE  ->  decode  ->  detect  ->  lift  ->  C files

Coaster is a Microsoft C (large-model) DOS program: a flat MZ image (no
overlays) holding several _TEXT code segments grouped below DGROUP, then the
initialised data + BSS. Compared with the civ driver this one:

  * auto-detects the code/data boundary from the relocation table (the most
    frequently-referenced segment value is DGROUP) and refuses to lift the data
    region as if it were code;
  * augments Microsoft-C prologue detection (PUSH BP / MOV BP,SP) with
    *call-target* boundaries, so the C run-time library - which is full of
    leaf routines that never set up a BP frame - gets carved into real
    functions instead of one 25 KB blob.

Output: RecompiledFuncs/coaster_recomp_NNN.c + coaster_recomp.h + coaster_stubs.c

Part of the Coaster Recomp project (sp00nznet/coaster)
"""

import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from decode16 import Decoder, OpType
from analyze import Analyzer
from lift import Lifter


HEADER = """\
/*
 * {filename} - Recompiled Coaster code
 *
 * AUTO-GENERATED by tools/recomp.py - DO NOT EDIT
 * Source: COASTER.EXE (Roller Coaster Construction Set, 1993)
 *
 * Part of the Coaster Recomp project (sp00nznet/coaster)
 */

#include "recomp/cpu.h"

/* Forward declarations */
{forward_decls}

/* DOS/BIOS interrupt handlers (implemented in dos_compat.c) */
extern void dos_int21(CPU *cpu);
extern void bios_int10(CPU *cpu);
extern void bios_int16(CPU *cpu);
extern void mouse_int33(CPU *cpu);
extern void int_handler(CPU *cpu, uint8_t num);

/* Port I/O (implemented in dos_compat.c) */
extern void port_out8(CPU *cpu, uint16_t port, uint8_t value);
extern uint8_t port_in8(CPU *cpu, uint16_t port);

"""


def detect_dgroup(data, hdr_size):
    """The DGROUP segment base = the load-relative segment value referenced by
    the most relocations (it is the program's default data segment, pointed at
    by every global/static access). Everything at or above it is data."""
    nrel = struct.unpack_from('<H', data, 6)[0]
    reloff = struct.unpack_from('<H', data, 24)[0]
    counts = {}
    for i in range(nrel):
        o, s = struct.unpack_from('<HH', data, reloff + i * 4)
        fa = hdr_size + s * 16 + o
        if fa + 2 <= len(data):
            v = struct.unpack_from('<H', data, fa)[0]
            counts[v] = counts.get(v, 0) + 1
    if not counts:
        return None
    return max(counts, key=counts.get)


def collect_call_targets(data, code_start, code_end, funcs):
    """Harvest near-call destinations from the (reliably decoded) bodies of the
    prologue-detected functions. These are genuine entry points and let us split
    the BP-frameless run-time blob into real functions."""
    targets = set()
    for f in funcs:
        if f.start >= code_end:
            continue
        end = min(f.end, code_end)
        dec = Decoder(data[f.start:end], base_offset=f.start)
        for inst in dec.decode_range(0, end - f.start):
            if inst.mnemonic == 'call' and inst.op1 and inst.op1.type in (OpType.REL16, OpType.REL8):
                t = f.start + inst.op1.disp
                if code_start <= t < code_end:
                    targets.add(t)
    return targets


def recompile(exe_path, output_dir, funcs_per_file=50):
    print("=" * 62)
    print("  Coaster Static Recompiler  -  COASTER.EXE -> C")
    print("=" * 62)

    with open(exe_path, 'rb') as f:
        data = f.read()
    print(f"\nLoaded {exe_path} ({len(data)} bytes)")

    hdr_size = struct.unpack_from('<H', data, 8)[0] * 16
    dgroup = detect_dgroup(data, hdr_size)
    code_start = hdr_size
    code_end = hdr_size + dgroup * 16 if dgroup else len(data)
    print(f"  header        : 0x{hdr_size:X}")
    print(f"  DGROUP segment: 0x{dgroup:04X}  (data begins here)")
    print(f"  code region   : 0x{code_start:X} .. 0x{code_end:X}  "
          f"({(code_end - code_start) / 1024:.1f} KB)")

    # --- Phase 1: detect functions (prologues + call targets) ---
    print("\n--- Phase 1: Analysis ---")
    analyzer = Analyzer(data)
    analyzer.detect_all_functions()
    analyzer.extract_strings()
    prologue_funcs = [f for f in analyzer.functions if f.start < code_end]

    call_targets = collect_call_targets(data, code_start, code_end, prologue_funcs)
    entry_cs = struct.unpack_from('<H', data, 22)[0]
    entry_ip = struct.unpack_from('<H', data, 20)[0]
    entry_off = hdr_size + entry_cs * 16 + entry_ip

    starts = set(f.start for f in prologue_funcs if f.start < code_end)
    starts |= {t for t in call_targets if code_start <= t < code_end}
    starts.add(entry_off)
    starts = sorted(starts)
    print(f"  prologue functions : {len(prologue_funcs)}")
    print(f"  call-target splits : {len(call_targets)}")
    print(f"  total entry points : {len(starts)}")

    # far-ness of a prologue function carries over to any split that starts inside it
    far_map = {}
    for f in prologue_funcs:
        far_map[f.start] = f.is_far

    # Build the final function table: start -> end (next start, clamped)
    funcs = []
    for i, s in enumerate(starts):
        e = starts[i + 1] if i + 1 < len(starts) else code_end
        e = min(e, code_end)
        if e <= s:
            continue
        # inherit far-ness from the containing prologue function, if any
        is_far = far_map.get(s, False)
        if not is_far:
            for pf in prologue_funcs:
                if pf.start <= s < pf.end and pf.is_far:
                    is_far = True
                    break
        funcs.append((s, e, is_far))

    name_of = lambda off: f'sub_{off:06X}'
    known_funcs = {s: name_of(s) for s, _, _ in funcs}

    # --- Phase 2: lift ---
    print("\n--- Phase 2: Lifting ---")
    os.makedirs(output_dir, exist_ok=True)
    all_lifted = []
    all_names = set()
    errors = 0
    for s, e, is_far in funcs:
        code = data[s:e]
        dec = Decoder(code, base_offset=s)
        instructions = dec.decode_range(0, len(code))
        lifter = Lifter(overlay_bases={}, hdr_size=hdr_size, known_funcs=known_funcs)
        name = name_of(s)
        try:
            c_code = lifter.lift_function(name, instructions, s, is_far)
            all_lifted.append((s, e, name, c_code, lifter.func_calls))
            all_names.add(name)
        except Exception as ex:
            print(f"  error lifting {name}: {ex}")
            errors += 1
    print(f"Lifted {len(all_lifted)} functions ({errors} errors)")

    # referenced names -> forward declarations
    referenced = set(all_names)
    for _, _, _, _, calls in all_lifted:
        referenced.update(calls)
    forward_decls = '\n'.join(f'void {n}(CPU *cpu);' for n in sorted(referenced))

    # exclude hand-written implementations
    import re
    impl_funcs = set()
    impl_path = os.path.join(output_dir, 'coaster_impl.c')
    if os.path.exists(impl_path):
        with open(impl_path) as f:
            for m in re.finditer(r'^void\s+(\w+)\s*\([^)]*\)\s*\{', f.read(), re.M):
                impl_funcs.add(m.group(1))
        print(f"  {len(impl_funcs)} hand-written impls in coaster_impl.c (excluded)")

    # --- Phase 3: output ---
    print("\n--- Phase 3: Output ---")
    total_files = 0
    for fi, base in enumerate(range(0, len(all_lifted), funcs_per_file)):
        batch = all_lifted[base:base + funcs_per_file]
        filename = f'coaster_recomp_{fi:03d}.c'
        with open(os.path.join(output_dir, filename), 'w') as out:
            out.write(HEADER.format(filename=filename, forward_decls=forward_decls))
            for s, e, name, c_code, _ in batch:
                if name in impl_funcs:
                    out.write(f'\n/* {name}: excluded (hand-written in coaster_impl.c) */\n')
                    continue
                out.write(f'\n/* {name}: original 0x{s:06X}-0x{e:06X} ({e - s} bytes) */\n')
                out.write(c_code)
                out.write('\n')
        total_files += 1
    print(f"  wrote {total_files} coaster_recomp_*.c files")

    # stubs for unresolved references
    hal_funcs = {'dos_int21', 'bios_int10', 'bios_int16', 'mouse_int33',
                 'int_handler', 'port_out8', 'port_in8'}
    unresolved = referenced - all_names - impl_funcs - hal_funcs
    if unresolved:
        with open(os.path.join(output_dir, 'coaster_stubs.c'), 'w') as out:
            out.write('/*\n * coaster_stubs.c - Stubs for unresolved references\n')
            out.write(' * AUTO-GENERATED by tools/recomp.py\n *\n')
            out.write(' * Referenced by recompiled code but not yet identified as a function:\n')
            out.write(' * MSC run-time routines, jump-table-only targets, far call thunks.\n')
            out.write(' * Each logs once when first called.\n */\n\n')
            out.write('#include "recomp/cpu.h"\n#include <stdio.h>\n\n')
            for n in sorted(unresolved):
                ret = 4 if n.startswith('far_') else 2
                out.write(f'void {n}(CPU *cpu) {{\n')
                out.write('    (void)cpu;\n')
                out.write('    static int c = 0;\n')
                out.write(f'    if (c++ == 0) fprintf(stderr, "[STUB] {n}\\n");\n')
                out.write(f'    cpu->sp += {ret};\n}}\n\n')
        print(f"  coaster_stubs.c: {len(unresolved)} stubs")

    # dispatch table: maps a load-relative code address to its C function, so
    # the lifter's recomp_dispatch() can resolve indirect / computed far calls.
    LOAD_SEG = 0x0110
    with open(os.path.join(output_dir, 'coaster_dispatch.c'), 'w') as out:
        out.write('/*\n * coaster_dispatch.c - indirect/computed-call resolver\n')
        out.write(' * AUTO-GENERATED by tools/recomp.py\n *\n')
        out.write(' * The recompiled code turns "call far ptr [reg]" and friends into\n')
        out.write(' * recomp_dispatch(cpu, seg, off); this maps that target back to the\n')
        out.write(' * right C function via a sorted table of load-relative addresses.\n */\n\n')
        out.write('#include "recomp/cpu.h"\n#include "coaster_recomp.h"\n#include <stdio.h>\n\n')
        out.write('typedef void (*recomp_fn)(CPU *);\n')
        out.write('typedef struct { uint32_t addr; recomp_fn fn; } DispatchEntry;\n\n')
        out.write('static const DispatchEntry g_dispatch[] = {\n')
        table = sorted((s - hdr_size, name_of(s)) for s, _, _ in funcs)
        for addr, nm in table:
            out.write(f'    {{ 0x{addr & 0xFFFFFFFF:06X}, {nm} }},\n')
        out.write('};\n')
        out.write(f'static const int g_dispatch_count = {len(table)};\n')
        out.write(f'#define COASTER_LOAD_BASE 0x{LOAD_SEG * 16:X}u\n\n')
        out.write('''static recomp_fn lookup(uint32_t key)
{
    int lo = 0, hi = g_dispatch_count - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (g_dispatch[mid].addr == key) return g_dispatch[mid].fn;
        if (g_dispatch[mid].addr < key)  lo = mid + 1;
        else                             hi = mid - 1;
    }
    return 0;
}

/* seg:off may be load-relative (baked-in direct far calls) or carry the load
 * segment (far pointers read from relocated memory); try both interpretations. */
void recomp_dispatch(CPU *cpu, uint16_t seg, uint16_t off)
{
    uint32_t flat = ((uint32_t)seg << 4) + off;
    recomp_fn fn = lookup(flat);
    if (!fn && flat >= COASTER_LOAD_BASE) fn = lookup(flat - COASTER_LOAD_BASE);
    if (fn) { fn(cpu); return; }
    {
        static int c = 0;
        if (c++ < 32)
            fprintf(stderr, "[DISPATCH] unresolved %04X:%04X (flat %05X)\\n", seg, off, flat);
    }
    cpu->sp += 4; /* simulate far ret so the caller can unwind */
}
''')
    print(f"  coaster_dispatch.c: {len(table)}-entry table")

    # master header
    with open(os.path.join(output_dir, 'coaster_recomp.h'), 'w') as out:
        out.write('/* coaster_recomp.h - Master header (AUTO-GENERATED) */\n')
        out.write('#ifndef COASTER_RECOMP_H\n#define COASTER_RECOMP_H\n\n')
        out.write('#include "recomp/cpu.h"\n\n')
        for n in sorted(all_names):
            out.write(f'void {n}(CPU *cpu);\n')
        out.write(f'\n#define COASTER_ENTRY_POINT {name_of(entry_off)}\n')
        out.write(f'#define COASTER_DGROUP 0x{dgroup:04X}\n')
        out.write('\n#endif\n')

    print("\n--- Summary ---")
    print(f"  functions : {len(all_lifted)}")
    print(f"  files     : {total_files} .c + 1 .h")
    print(f"  entry      : {name_of(entry_off)}  (0x{entry_off:06X})")
    print(f"  errors    : {errors}")


def main():
    if len(sys.argv) < 2:
        print("usage: recomp.py <COASTER_unpacked.exe> [output_dir] [funcs_per_file]")
        sys.exit(1)
    exe = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) >= 3 else 'RecompiledFuncs'
    fpf = int(sys.argv[3]) if len(sys.argv) >= 4 else 50
    recompile(exe, out, fpf)


if __name__ == '__main__':
    main()
